@startuml user_login

hide footbox

actor User
participant "Login Page" as UI
participant "Django\nURL Dispatcher" as API
participant "Login\nView" as view_login
participant "User\nSerializer" as serializer_user
database "users" as table_users

activate User
activate UI
User -> UI: Enter username & password
User -> UI: Tap Login button

UI -> UI: Validate input

alt Valid input
    UI -> API: POST auth/login/ \n(username, password)
    activate API

    API -> view_login: post(request)
    activate view_login

    view_login -> serializer_user: validate(data)
    activate serializer_user

    serializer_user -> table_users: check_credentials \n(username, password, is_active)
    activate table_users

    table_users --> serializer_user: user_data
    deactivate table_users

    serializer_user --> view_login: valid_user / error
    deactivate serializer_user

    alt Authentication successful
        view_login -> view_login: create_session(user)
        view_login --> API: 200 OK (jwt token)
        API --> UI: 200 OK
        UI -> UI: Navigate to HomePage
    else Authentication failed
        view_login --> API: 401 Unauthorized
        deactivate view_login
        API --> UI: 401 Unauthorized
        deactivate API
        UI --> User: Show error message
        deactivate UI
    end
end

deactivate User

@enduml
