@startuml account_page

hide footbox

actor User
participant "Account Page" as UI

participant "Django\nURL Dispatcher" as API
participant "User\nView" as view
participant "User\nSerilizer" as serializer
database "user" as user


User -> UI: Open Account Page
activate User
activate UI
UI -> API: GET /profile \nwith user_id
activate API

' API Call
API -> view: get(user_id)
activate view
view -> serializer: get(request)
activate serializer
serializer -> user: serializer(query_set)
activate user

user --> serializer: user_data
deactivate user
serializer --> view: user_data
deactivate serializer
view --> API: response()
deactivate view

API --> UI: user profile data
UI -> User: Display user info and settings

opt Edit Profile
    User -> UI: Tap Edit Profile
    UI -> UI: Navigate to Edit Profile Page
end

@enduml