@startuml db-user

hide circle
hide empty members

skinparam linetype ortho

entity user {
    * **user_id: INT <<PK>>**
    user_name: VARCHAR(100)
    email: VARCHAR(100)
    profile_image: VARCHAR(255)
}

entity post {
    * **post_id: INT <<PK>>**
    text_content: VARCHAR(500)
    image: VARCHAR(255)
    timestamp: DATETIME
    --
    * user_id: INT <<FK>>
}

entity comment {
    * **comment_id: INT <<PK>>**
    text_content: VARCHAR(500)
    timestamp: DATETIME
    --
    * user_id: INT <<FK>>
    * post_id: INT <<FK>>
}

entity like {
    * **like_id: INT <<PK>>**
    timestamp: DATETIME
    --
    * user_id: INT <<FK>>
    * post_id: INT <<FK>>   
}

user ||..o{ post
user ||..o{ comment
user ||..o{ like
post ||..o{ comment
post ||..o{ like

entity user_event {
    * **event_id: INT <<PK>>**
    event_name: VARCHAR(100)
    description: VARCHAR(500)
    start_date: DATETIME
    end_date: DATETIME
    latitude: DECIMAL(18, 15)
    longitude: DECIMAL(18, 15)
    --
    * post_id: INT <<FK>>
}

user_event ||--|| post


entity user_place {
    * **place_id: INT <<PK>>**
    place_name: VARCHAR(100)
    latitude: DECIMAL(18, 15)
    longitude: DECIMAL(18, 15)
    --
    * user_id: INT <<FK>>
    * place_type_id: INT <<FK>>
}

user }o..o{ user_place

entity favorite_routes {
    --
    * user_id: INT <<FK>>
    * line_id: INT <<FK>>
}

entity favorite_stops {
    --
    * user_id: INT <<FK>>
    * stop_id: INT <<FK>>
}

user }o..o{ favorite_routes
user }o..o{ favorite_stops
favorite_routes }|..|| transit_lines
favorite_stops }|..|| transit_stops

entity feedbacks {
    * **feedback_id: INT <<PK>>**
    feedback_type: VARCHAR(100)
    text_content: VARCHAR(500)
    image: VARCHAR(100)
    timestamp: DATETIME
    --
    * user_id: INT <<FK>>
}

user ||..o{ feedbacks

' entity user_configuration {
'     config_key: VARCHAR(100)
'     config_value: VARCHAR(255)
'     --
'     * user_id: INT <<FK>>
' }


entity notification {
    * **device_id: INT <<PK>>**
    --
    * user_id: INT <<FK>>
    * fcm_device_id: INT <<FK>>
}

user }o..o{ notification


@enduml
